## Libreria Numpy (numeric python)

#### Libreria para aplicaciones de calculo numérico y computacion científica para matrices.

* Reemplazo de MatLab.
* Permite el calculo matricial de manera vectorizada. Estructuras de dimension n. Consume menos memoria y aporta facilidad de uso.
* Trabaja con estructuras homogeneas.
* Solo admite numeros (int, float, complex). Solo un tipo de dato para cada estructura!! Estructuras numericas homogeneas.
* Esta programado en Fortran y C

In [ ]:
import subprocess # para simular una linea de comandos

# split() para que convierta la salida en lista
# capture_output para capturar la salida, en caso de error es muy util
# text=True lo devuelve como texto

In [ ]:
p=subprocess.run('python --version'.split(), capture_output=True, text=True)
p.stdout.replace("\n","")

In [ ]:
# Lo uso para instalar numpy. Como ya la tengo instalada me indica que ya la tengo instalada.

p=subprocess.run('pip install numpy', capture_output=True, text=True)
p.stdout.replace("\n","")

In [ ]:
# Otra forma de instalar simulando la consola de comandos con !
! pip install numpy 

In [1]:
# Cargar numpy

import numpy as np

### Arreglos

* Vector unidimensional
* Matriz multidimensional

In [2]:
l=list(range(10))
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
l_np=np.array(l) # convierte la lista a array de numpy
l_np

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
type(l)

list

In [5]:
type(l_np) # son diferentes estructuras las listas y los arrays. Los arrays de numpy son mas eficientes

numpy.ndarray

In [6]:
len(l), len(l_np)

(10, 10)

In [7]:
# Teniendo una lista y un array con los mismos elementos
l=[0,1,2,3]
lnp=np.array(l)
l, lnp

([0, 1, 2, 3], array([0, 1, 2, 3]))

In [8]:
# El tipo de objeto es diferente
type(l), type(lnp)

(list, numpy.ndarray)

In [9]:
# Aunque los elementos sean iguales
l[:len(l)]==lnp[:lnp.size]

array([ True,  True,  True,  True])

In [10]:
# Algunas propiedades de los arrays

In [11]:
l_np.ndim # dimensiones de la matriz (en este caso es un vector)

1

In [12]:
l_np.size # Nro de objetos del array vectorizado. Es mas eficiente que len. Es la funcion para obtener la longitud del array

10

In [13]:
l_np.shape # devuelve ambos datos

(10,)

In [14]:
l

[0, 1, 2, 3]

In [15]:
# para mostrar un elemento
l_np[0]

0

In [16]:
# Muestra todo
l_np[:l_np.size]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
l_np

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Nota: las operaciones de deben realizar sobre el mismo tipo de objeto. Vectorizados o sin vectorizar. No se pueden combinar en las operaciones.

Nota: Numpy trabaja con numeros flotantes. Es mas eficiente con variables flotantes.

In [18]:
np.arange(10,15,1) # equivalente a range de python con listas

array([10, 11, 12, 13, 14])

In [19]:
[0]*4 # con listas

[0, 0, 0, 0]

In [20]:
np.zeros(4) # con arrays. Observar que son float

array([0., 0., 0., 0.])

In [21]:
np.ones(3)

array([1., 1., 1.])

In [ ]:
# Para generar este vector
[0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9]

In [ ]:
range(0.1,1.0,0.1) range solo vale para enteros

In [22]:
[i/10 for i in range(1,11)]

[0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]

In [23]:
[0.05+i/10 for i in range(1,11)] # observar que python sin vectorizar no trata bien los decimales. Para entero guay pero flotante ko.
                                # Maneja una precision n

[0.15000000000000002,
 0.25,
 0.35,
 0.45,
 0.55,
 0.65,
 0.75,
 0.8500000000000001,
 0.9500000000000001,
 1.05]

In [24]:
# con vector numpy
np.linspace(0.1,1,10)

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [25]:
np.linspace(0.1,1,10)+0.05 # estos resultados si son correctos

array([0.15, 0.25, 0.35, 0.45, 0.55, 0.65, 0.75, 0.85, 0.95, 1.05])

In [26]:
a,b=[0,1,2],[1,1,1]

In [27]:
a,b

([0, 1, 2], [1, 1, 1])

In [28]:
# Si quiero obtener a*10+b*0.5
# Con listas de python tengo que definir una funcion. 
# Con vectores:

In [29]:
a=np.array([0,1,2])
b=np.array([1, 1, 1])

In [30]:
c=a*10+b*0.5 # Con numpy es directo
c

array([ 0.5, 10.5, 20.5])

In [31]:
d=(3+a)-(b-0.5)
d

array([2.5, 3.5, 4.5])

In [32]:
e=a*b
e

array([0, 1, 2])

In [33]:
a=np.array([0,1,2])
b=np.array([1, 0, 1])

In [34]:
f=a/b # en divisiones con indeterminacion matematica avisa y coherciona a calculo simbolico
f

C:\Users\carolina\AppData\Local\Temp\ipykernel_10712\2014004919.py:1: RuntimeWarning: divide by zero encountered in true_divide
  f=a/b # en divisiones con indeterminacion matematica avisa y coherciona a calculo simbolico


array([ 0., inf,  2.])

In [35]:
a=[0,1,2]
b=[1,2,3]

In [36]:
a.extend(b)
a

[0, 1, 2, 1, 2, 3]

In [37]:
a=np.array([0,1,2])
b=np.array([1,2,3])

In [38]:
a,b

(array([0, 1, 2]), array([1, 2, 3]))

In [39]:
np.concatenate((a,b)) # 

array([0, 1, 2, 1, 2, 3])

In [40]:
a[a<2] # devuelve los elementos del array que cumplen la condicion

array([0, 1])

In [41]:
l_np[l_np>=3]

array([3, 4, 5, 6, 7, 8, 9])

In [42]:
l_np[l_np%2==0] # numeros pares del vector

array([0, 2, 4, 6, 8])

#### Operadores logicos de Numpy

* mayor y menor son iguales: >, >=, <, <=
* and es &
* or es |

In [43]:
# En python 

q=9
if q>6 and q%2!=0:
    print(q)

9


In [46]:
q=9
if q>6 & q%2!=0:   # en este ide & no funciona 
    print(q)   

In [47]:
# En numpy

l_np[(l_np%2!=0) & (l_np>=3)] # las condiciones requieren de encerrar con () las partes 

array([3, 5, 7, 9])

In [48]:
l_np[(l_np<2) | (l_np>6)] # Mayores de 6 o menores a 2


array([0, 1, 7, 8, 9])

#### Matrices

In [49]:
m=[[1,2,3],[4,5,6]]

In [50]:
m_np=np.array(m)
m_np

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
# Para contar la totalidad de elementos de la matriz

# En Python
len(m[0])+len(m[1])

6

* Propiedades de tamaño

In [52]:
# En Numpy

m_np.size # cuenta todos los elementos de la matriz

6

In [53]:
m_np.shape # primera dimension tiene 2 elementos (son 2 filas)
           # segunda dimension tiene 3 elementos (son 3 columnas en cada fila)

(2, 3)

In [54]:
m_np.ndim # filas y columnas son dos dimensiones

2

In [55]:
t=[ [[1,2],[3,4],[5,6]] , [[1,2],[3,4],[5,6]],  [[1,2],[3,4],[5,6]], [[1,2],[3,4],[5,6]] ]
tnp=np.array(t)
tnp

array([[[1, 2],
        [3, 4],
        [5, 6]],

       [[1, 2],
        [3, 4],
        [5, 6]],

       [[1, 2],
        [3, 4],
        [5, 6]],

       [[1, 2],
        [3, 4],
        [5, 6]]])

In [56]:
tnp.size # 24 elementos en total 4 elementos x 6 elementos internos c/u (3x2 elementos internos c/u)

24

In [57]:
tnp.ndim 
# 1º dimension tiene 4 elementos
# 2º dimension tiene 3 elementos en c/u de los 4
# 3º dimension tiene 2 elementos en c/u de los 3

3

In [58]:
# Total elementos (size) = 2 (dim3) X 3 (dim2) X 4 (dim1)

In [59]:
tnp.shape # cantidad de elementos por cada dimension (es explicacion anterior)

(4, 3, 2)

In [60]:
tnp[0],        tnp[0,0],                    tnp[0,0,0] 
# 1º elemento, 1º elemento del 1º elemento, 1º elemento del 1º elemento del 1º elemento

(array([[1, 2],
        [3, 4],
        [5, 6]]),
 array([1, 2]),
 1)

* Obtener elementos

In [61]:
m_np

array([[1, 2, 3],
       [4, 5, 6]])

In [62]:
m_np[0] # primera fila

array([1, 2, 3])

In [63]:
m_np[:,1] # segunda columna (todas las filas)

array([2, 5])

In [64]:
m_np[1,1] # segunda fila, segunda columna

5

In [65]:
m_np[1,2] # ultimo elemento de la matriz

6

In [66]:
p=np.arange(10)
p

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
p[:len(p)] # muestra desde el comienzo hasta el len. Recordar que len es mas propio de python o sea para listas

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
len(p), p.size

(10, 10)

In [69]:
p[:p.size] # muestra desde el comienzo hasta el fin. Esto es mas correcto que usar len(p)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

* Borrar elementos de una Matriz

In [72]:
m_np

array([[1, 2, 3],
       [4, 5, 6]])

In [73]:
np.delete(m_np, 1, axis=0) # elimina la fila 1 
# queda solo la fila 0

array([[1, 2, 3]])

In [74]:
np.delete(m_np, 1, axis=1) # elimina la columna 1 
# quedan la primera y ultima columna porque elimino la 1 (segunda)

array([[1, 3],
       [4, 6]])

In [75]:
m_np # np.delete() no borra directamente si no ponemos inplace=True 

array([[1, 2, 3],
       [4, 5, 6]])

* Matriz identidad, matriz de ceros y de unos

In [76]:
np.ones([3,3]) # Matriz 3x3 de unos

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [77]:
np.zeros([3,3]) # Matriz 3x3 de ceros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [78]:
np.eye(3) # esta es la matriz identidad de 3. Siempre son cuadradas.

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

* Concatenar o unir matrices

In [79]:
np.concatenate((m_np, np.eye(3)), axis=0) # concatena por filas. Tienen que tener mismo numero de columnas.

array([[1., 2., 3.],
       [4., 5., 6.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [80]:
np.concatenate((np.zeros([3,3]), np.ones([3,3])), axis=1) # concatena por columnas. Tienen que tener mismo numero de filas.

array([[0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])

* Redimensionar un array (las matrices origen y redimensionada deben tener el mismo tamaño (size))

In [1]:
import numpy as np

In [2]:

k=np.arange(10,16,1) # matriz unidimensional con 6 elementos. Es como range (inicio, final+1, paso)
k

array([10, 11, 12, 13, 14, 15])

In [82]:
np.reshape(k,newshape=(2,3)) # convierto a matriz de 2x3 (6 elementos). La primera dimension tiene 2 elementos y la segunda 3.

array([[10, 11, 12],
       [13, 14, 15]])

In [3]:
k.reshape(2,3) # convierte a matriz de 2x3

array([[10, 11, 12],
       [13, 14, 15]])

* Aplanar una Matriz

In [4]:
k.ravel()

array([10, 11, 12, 13, 14, 15])


* Apilar matrices vertical u horizontalmente


In [83]:
np.vstack((np.zeros([3,3]), np.ones([3,3]))) # apila las matrices en vertical por filas o sea por debajo. 
# Hace lo mismo que concatenate con axis = 0 pero para matrices de dim > 30 es mas rapida 

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [84]:
np.hstack((np.zeros([3,3]), np.ones([3,3]))) # apila las matrices en horizontal, por columnas o sea lateralmento hacia la derecha. 
# Hace lo mismo que concatenate con axis=1 pero para matrices de dim > 30 es mas rapida 

array([[0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])

Ejercicio: 

crear la redimension de un vector de elementos enteros comprendido en el intervalo [1,25) a dos filas

In [86]:
v=np.arange(1,25) # son 24 elementos porque comienza en 1
v

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [87]:
w=np.reshape(v,newshape=(2,int(v.size/2))) # serian 2 las filas, y las columnas se calculan como size/filas o sea size/2
w

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [88]:
w=np.reshape(v,newshape=(2,v.size//2)) # con division entera, que devuelve un entero
w

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])


* Particion de una matriz


In [89]:
w # dada esta matriz

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [90]:
np.hsplit(w,3) # parte la matriz verticalmente en tres partes del mismo tamaño cada una

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [91]:
r=np.hsplit(w,3) 
# Esto es una LISTA de matrices, que tendra tantos elementos 'matrices' como divisiones hayamos indicado en la particion
r

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [95]:
type(r)

list

In [96]:
nr=np.array(r)

In [97]:
nr # ahora si es un array

array([[[ 1,  2,  3,  4],
        [13, 14, 15, 16]],

       [[ 5,  6,  7,  8],
        [17, 18, 19, 20]],

       [[ 9, 10, 11, 12],
        [21, 22, 23, 24]]])

In [98]:
nr.shape # 3 dimensiones

(3, 2, 4)

In [99]:
nr.size # elementos totales (producto de elementos de cada dimension)

24

In [102]:
nr.ndim

3

In [103]:
r[0]

array([[ 1,  2,  3,  4],
       [13, 14, 15, 16]])

In [104]:
r[1]

array([[ 5,  6,  7,  8],
       [17, 18, 19, 20]])

In [105]:
r[2]

array([[ 9, 10, 11, 12],
       [21, 22, 23, 24]])

In [106]:
w

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [107]:
# Otra particion de la matriz

np.hsplit(w,(3,6)) # Parte verticalmente la matriz despues de la 3ra y la 6ta columna. El resto queda en el ultimo array del vector

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4,  5,  6],
        [16, 17, 18]]),
 array([[ 7,  8,  9, 10, 11, 12],
        [19, 20, 21, 22, 23, 24]])]

In [108]:
np.hsplit(w,(3,6))[2] # El resto queda en el ultimo array del vector

array([[ 7,  8,  9, 10, 11, 12],
       [19, 20, 21, 22, 23, 24]])

* Numpy contiene Math 

IMPORTANTE: FUNCIONES DE ALEATORIEDAD (muestra aleatoria)
    
    RANDOM
    
    np.random.random((2,4)) # esto crea una matriz aleatoria de 2x4 
    np.random.randint(11,size = (2,4)) # rango dentro del cual escoge los aleatorios y el tamaño de la matriz.
     
    SAMPLE (observar que va sin np.)
    
    random.sample(list(lista), k, counts = None) 
    
    # lista (convertir a lista para que funcione) de k elementos extraídos sin repetición de la secuencia population
    # (si en la lista hay elementos repetidos, si que se podrán repetir). 
    
    * lista: Secuencia de la que extraer la muestra (hay que cohersionar a lista sino da un error).
    * k: Número de elementos a extraer.
    * counts: (Opcional) Frecuencias absolutas de los elementos de population si quiero repeticiones.

        
    # Si population contiene elementos repetidos, cada uno de ellos es susceptible de ser escogido por separado !!

    # Los elementos repetidos pueden ser especificados uno por uno, o mediante el parámetro counts. 
    # Éste, de existir, deberá contener la frecuencia absoluta de cada uno de los elementos de population, 
    # lo que supone que el número de elementos de population y de counts deberá coincidir. 
   
    #Así, por ejemplo, el siguiente código:
        random.sample(list(["A", "B", "C"]), k = 2, counts = [3, 2, 1])
    #es equivalente a:
        random.sample(list(["A", "A", "A", "B", "B", "C"]), k = 2)
        
    CHOICE para listas con elementos de distinto tipo (no sirve si se necesita una muestra sin repeticion)
    
    np.random.choice(lista,size=2) # devuelve elementos de la lista pero repitiendo. La lista puede contener tipos variados
    np.random.choice(x.shape[0], 8, replace=False) # con el replace se puede elegir sin repeticion 
    
    FUNCIONES PARA FIJAR SEMILLA 
    
    np.random.seed=0
    random.seed(0)
    
    Ej: random.seed(0)
        random.sample(range(10),k=4)
        

In [13]:
import numpy as np
import random

In [85]:
random.seed(0)
random.sample(range(10),k=4)  # siempre dan los mismos 4 numeros

[6, 9, 0, 2]

In [60]:
random.sample(list(["A", "B", "C"]), k = 2, counts = [3, 2, 1])

['B', 'C']

In [65]:
random.sample(list(["A", "A", "A", "B", "B", "C"]), k = 2)

['B', 'B']

In [67]:
random.sample(list(["A", "B", "C"]), k = 2) 
# en este caso nunca se repetiran porque en la lista no hay repetidos y no indique el parametro counts con las frecuencias

['C', 'A']

In [79]:
 np.random.choice(list(["A", "B", "C"]),size=2)

array(['A', 'C'], dtype='<U1')

In [109]:
w.sum() # Sumar todos los elementos

300

In [110]:
np.sqrt(w) # raiz cuadrada

array([[1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
        2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
        3.31662479, 3.46410162],
       [3.60555128, 3.74165739, 3.87298335, 4.        , 4.12310563,
        4.24264069, 4.35889894, 4.47213595, 4.58257569, 4.69041576,
        4.79583152, 4.89897949]])

In [111]:
np.mean(w) # media 

12.5

In [112]:
np.std(w) # desviacion tipica o estandard

6.922186552431729

In [113]:
np.var(w) # varianza  

47.916666666666664

In [114]:
w.max(), w.min() # Maximo y minimo

(24, 1)

In [115]:
np.random.random((2,4)) # aleatorios entre 0 y 1

array([[0.08603313, 0.59681691, 0.32373949, 0.89466442],
       [0.56170368, 0.67049232, 0.62831322, 0.07037954]])

Ejercicio: crear la matriz aleatoria de tamaño mxn (2x4) en decenas de numeros enteros

In [116]:
np.round(np.random.random((2,4))*10,0) # el 0 indica la precision del redondeo (2 serian dos decimales)


array([[2., 4., 3., 3.],
       [4., 7., 5., 2.]])

In [117]:
np.ceil(np.random.random((2,4))*10) # redondeo al alza (entero siguiente en este caso)


array([[ 9.,  6.,  5.,  2.],
       [ 2.,  5.,  1., 10.]])

In [118]:
np.trunc(np.random.random((2,4))*10) # trunca la parte decimal (redondeo a la baja)

array([[7., 8., 9., 5.],
       [7., 8., 7., 9.]])

In [119]:
a=np.random.random((1,1))
a, np.round(a), np.ceil(a), np.trunc(a)

(array([[0.05711883]]), array([[0.]]), array([[1.]]), array([[0.]]))

In [120]:
np.random.randint(11,size = (2,4)) # se le tiene que indicar la semilla y el tamaño de la matriz.
            # Parece ser que no es la semilla sino el rango dentro del cual escoge los aleatorios.


array([[3, 1, 4, 6],
       [4, 5, 5, 7]])

In [121]:
## Las anteriores matrices son de elementos float. El randint da enteros.

In [122]:
np.random.randint(3,size=(2,4)) # aleatorios < 3

array([[0, 0, 2, 2],
       [0, 1, 2, 0]])

In [123]:
# Matriz identidad de 4x4 con listas de python
dim=4
l=list()
for i in range(dim):
    m=list()
    for k in range(dim):
        if len(l)==k:
            m.append(1)
        else:
            m.append(0)
    l.append(m)
# Convierto a array de numpy 
l_np=np.array(l)
l_np

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [126]:
l_np.ndim, l_np.shape

(2, (4, 4))

In [124]:
# De forma directa con numpy
l_np2=np.eye(3) # crea la matriz identidad de 3x3
l_np2

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [128]:
l_np2.ndim, l_np2.shape, l_np2.size
#matriz de 2 dimensiones, cada dimension tiene 3 elementos c/u, total 9 elementos.

(2, (3, 3), 9)

* Valores unicos np.unique()

In [129]:
l=[[1,1,1],[1,1,1],[2,2,2],[2,2,2],[3,3,3],[3,3,3],[4,4,4]]

In [130]:
lnp=np.array(l)
lnp

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2],
       [3, 3, 3],
       [3, 3, 3],
       [4, 4, 4]])

In [131]:
np.unique(lnp) # valores unicos en toda la matriz (evalua a nivel de elementos contenidos en la totalidad de la matriz)

array([1, 2, 3, 4])

In [132]:
np.unique(lnp, axis=0) # filas unicas axis=0

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

In [133]:
np.unique(lnp, axis=1) # columnas unicas axis=1

array([[1],
       [1],
       [2],
       [2],
       [3],
       [3],
       [4]])

#### Matriz transpuesta, matriz adjunta, matriz inversa y determinante

In [134]:
m=[[2,1,0],[0,1,3],[2,1,1]]
M=np.array(m)
M

array([[2, 1, 0],
       [0, 1, 3],
       [2, 1, 1]])

* Matriz Traspuesta  (propiedad .T)

In [135]:
M.T

array([[2, 0, 2],
       [1, 1, 1],
       [0, 3, 1]])

* Determinante (metodo det()). Es un valor, no una matriz.


In [136]:
det=np.linalg.det(M) 
det

2.0

* Matriz inversa (aquella que al multiplicarse con la matriz original da por resultado la matriz identidad)

In [137]:
inv=np.linalg.inv(M)
inv

array([[-1. , -0.5,  1.5],
       [ 3. ,  1. , -3. ],
       [-1. ,  0. ,  1. ]])

NOTA: El producto de una matriz por su inversa es igual al matriz identidad.

In [139]:
np.matmul(M,inv) # np.matmul() multiplica matrices

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [140]:

# Calculo de la matriz inversa: EN EJERCICIO DE MATRICES
import numpy as np
w = np.array([[1,2,3],[4,5,6],[7,8,9]])
w

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [141]:
# Multiplicacion de los elementos de la diagonal ppal.
t1=1
for x in range(3):
    print(w[x])
    for y in range(3):
        if x==y:
            t1=t1*w[x,y]
t1

[1 2 3]
[4 5 6]
[7 8 9]


45

In [142]:
from numpy.linalg import det
det(w)

-9.51619735392994e-16